# A Google Container Engine (GKE) deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sibyl-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sibyl
    spec:

      volumes:
        - name: sibyl-nginx-configmap
          configMap:
            name: nginx

      containers:
          
        # Nginx web server
        - name: sibyl-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sibyl-nginx-configmap
              mountPath: /etc/nginx/conf.d/
              
        # Sibyl app server
        - name: sibyl-server
          image: stencila/sibyl-server
          imagePullPolicy: Always
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375
            - name: SIBYL_CLUSTER
              value: 'true'
            - name: SIBYL_FROM
              value: stencila/alpha
            - name: SIBYL_REGISTRY # TODO: configure gcr.io auth to be able to push
              value: gcr.io
            - name: TOKEN_SECRET # TODO: configure with a TOKEN_SECRET
              value: donttell
          ports:
            - containerPort: 3000

        # Docker-in-Docker (dind) to build bundle images
        - name: sibyl-docker
          image: docker:dind
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375

---

# Auto-scale the Sibyl deployment

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sibyl-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: sibyl-deployment
  minReplicas: 1
  maxReplicas: 10

---

# Rebuild images every day at midnight UTC
# 
# This would ideally be a CronJob but they are currently
# unsupported on GKE (except in "alpha" culsters). 
# See https://github.com/kubernetes/kubernetes.github.io/issues/2325#issuecomment-275763247
# 
# So we use a Deployment with a `cron` job running inside
# our `sibyl-builder` container

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sibyl-builder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sibyl-builder
    spec:
      containers:

        # Sibyl base image builder
        - name: sibyl-builder
          image: stencila/sibyl-builder
          imagePullPolicy: Always
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375

        # Docker-in-Docker (dind) to build base images
        - name: sibyl-docker
          image: docker:dind
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375

---

# Expose the Sibyl server

kind: Service
apiVersion: v1
metadata:
  name: sibyl-service
spec:
  type: NodePort
  selector:
    app: sibyl
  ports:
    - name: http
      protocol: TCP
      port: 80

---

# Provide a cluster ingress

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sibyl-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sibyl
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: sibyl-service
            servicePort: 80
